name: tapia
favicon: null
layout_spectrum: 0.50136
typography_spectrum: 0.58752
title: Tapia - your personal travel assistant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
