name: tapia
favicon: null
layout_spectrum: 0.9030676179099828
typography_spectrum: 0.40142538328655064
title: Tapia - your personal travel assistant
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7241824625525624
  lightness: 0.11422451096586883
  saturation: 0.4422461341600865
  rhythmicContrast: 0.7174854546319693
purpose: []
